### ISSUE TITLE
Extract Fuzzer invocation into dedicated fuzzing service

### ISSUE THREAD

**Issue by Rhernandez513** [sysec-uic/AutoPatch-LLM#7]
At present the fuzzer runs in memory, the goal of this story is to instead invoke async a fuzzing service via it's interface (to be defined)

First draft suggetion:

![Image](https://github.com/user-attachments/assets/d0a4ffc5-b85e-4178-a5e9-604b1e772de9)

graph TD
    E[Filesystem] --> CFG[Configuration]
    CFG[Configuration file:///app/config/config.json] -->|JSON Input| FS[Fuzzing Service]
    E[Filesystem] --> B[URL file:///app/data/program-file.txt] -->|Input| FS
    C[Array of Strings] -->|Input| FS
    FS -->|Output| D[Array of Strings]
    D[Array of Strings] --> G[Filesystem]
    D[Array of Strings] --> MQOUT[MQ Output Topic]

https://mermaid.live/edit#pako:eNp9Uk1PhDAQ_SuTnpflzsFEF9loRLLCXoQ9NFCgBtqmTI3sx3-3fKhrdrWXdt68N_MynQPJZcGIRypNVQ2Jnwmw5z4NeMO6vkPW7sBxbmAVrNOVFCWvjKbIpdhNzAscSqv0XNelSrn5mJmv5VtnZUO142McPcODUAaPEMRpYPZ7LiqImX7nOdv9ZeIu3b48_WpQUKSu0tLab50hscQPnHp8l5-Nprda0x5kCTFq2627SgviEY0MjrB_qZp4_vVysD43_T813ETbJA03MDWDRCqezxqyIC3TLeWF_ZvDgGUEa9ayjHj2WbCSmgYzkomTpVKDMu5FTjzUhi2IlqaqvwKj7JCYz-kwI-KVtOksqqh4lfInZgVHqcNpGcadOH0CCda0Nw

**Comment by Rhernandez513** [comment]
going to see about using golang for ease of high concurrency compared to python and we might just want to start many fuzzing processes concurrently, here we have some go code I will test later that has config to optionally spawn many fuzzers.  

This code should be considered pseduo code as it is LLM generated by using a few passes with increasing complex requirements, and while has been reviewed statically is has not yet been run dynamically:

```golang
example main.go

package main

import (
"bytes"
"encoding/json"
"fmt"
"os"
"os/exec"
"strings"
"sync"
"time"

"[github.com/eclipse/paho.mqtt.golang](http://github.com/eclipse/paho.mqtt.golang)"
)

type Command struct {
FilePath string   `json:"filePath"`
Args     []string `json:"args"`
}

type Config struct {
Mode       string    `json:"mode"`       // "concurrent" or "sequential"
FilePrefix string    `json:"filePrefix"` // Prefix for output filenames
MqttTopic  string    `json:"mqttTopic"`  // MQTT topic to publish to
Commands   []Command `json:"commands"`
}

func readConfig(file string) (*Config, error) {
// Open the config file
configFile, err := os.Open(file)
if err != nil {
return nil, fmt.Errorf("error opening config file: %w", err)
}
defer configFile.Close()

// Create a Config variable to hold the data
var config Config

// Decode the JSON into the Config structure
decoder := json.NewDecoder(configFile)
err = decoder.Decode(&config)
if err != nil {
return nil, fmt.Errorf("error decoding JSON: %w", err)
}

return &config, nil
}

func startSubprocess(filePath string, args []string, wg *sync.WaitGroup, outputs chan<- string) {
defer wg.Done() // Decrement the counter when the function completes

// Construct the command
cmd := exec.Command("./a.out", filePath, strings.Join(args, " "))

// Capture STDOUT
var out bytes.Buffer
cmd.Stdout = &out
cmd.Stderr = &out

// Run the command
err := cmd.Run()
if err != nil {
fmt.Printf("Error executing subprocess for file %s: %v\n", filePath, err)
outputs <- fmt.Sprintf("Error: %v\n", err)
return
}

// Send the captured output to the channel
outputs <- out.String()
fmt.Printf("Subprocess for file %s executed successfully with args: %v\n", filePath, args)
}

func writeToFile(filePrefix string, filePath string, output string) error {
// Generate a filename based on filePrefix and current Unix time
fileName := fmt.Sprintf("%s%s_%d.txt", filePrefix, strings.ReplaceAll(filePath, "/", "_"), time.Now().Unix())
file, err := os.Create(fileName)
if err != nil {
return fmt.Errorf("error creating file: %w", err)
}
defer file.Close()

// Write the output to the file
_, err = file.WriteString(output)
if err != nil {
return fmt.Errorf("error writing to file: %w", err)
}

fmt.Printf("Output written to file: %s\n", fileName)
return nil
}

func publishToMQTT(mqttTopic string, output string) error {
// Set up MQTT client options
opts := mqtt.NewClientOptions().AddBroker("tcp://localhost:1883").SetClientID("go-client")
client := mqtt.NewClient(opts)

// Connect to the MQTT broker
if token := client.Connect(); token.Wait() && token.Error() != nil {
return fmt.Errorf("error connecting to MQTT broker: %w", token.Error())
}

// Publish the output to the MQTT topic
token := client.Publish(mqttTopic, 0, false, output)
token.Wait()

// Disconnect from the broker
client.Disconnect(250)

fmt.Printf("Output published to MQTT topic: %s\n", mqttTopic)
return nil
}

func processOutput(filePrefix string, filePath string, mqttTopic string, output string, wg *sync.WaitGroup) {
defer wg.Done()

// Write to file
err := writeToFile(filePrefix, filePath, output)
if err != nil {
fmt.Println("Error writing to file:", err)
}

// Publish to MQTT
err = publishToMQTT(mqttTopic, output)
if err != nil {
fmt.Println("Error publishing to MQTT:", err)
}
}

func main() {
// Read configuration from the config file
config, err := readConfig("/app/config/config.json")
if err != nil {
fmt.Println("Error reading config:", err)
return
}

var wg sync.WaitGroup
outputs := make(chan string, len(config.Commands))

// Check if the mode is "concurrent" or "sequential"
if config.Mode == "concurrent" {
// Run all subprocesses concurrently
for _, command := range config.Commands {
wg.Add(1)

// Start the subprocess in a goroutine
go startSubprocess(command.FilePath, command.Args, &wg, outputs)
}
} else if config.Mode == "sequential" {
// Run all subprocesses sequentially
for _, command := range config.Commands {
startSubprocess(command.FilePath, command.Args, &wg, outputs)
}
} else {
fmt.Println("Invalid mode. Please specify either 'concurrent' or 'sequential'.")
return
}

// Wait for all Go routines to complete if running concurrently
wg.Wait()

// Close the channel after all subprocesses have completed
close(outputs)

// Process all collected outputs
if config.Mode == "concurrent" {
// Process outputs concurrently
for output := range outputs {
wg.Add(1)
go processOutput(config.FilePrefix, "/path/to/command", config.MqttTopic, output, &wg)
}
} else if config.Mode == "sequential" {
// Process outputs sequentially
for output := range outputs {
processOutput(config.FilePrefix, "/path/to/command", config.MqttTopic, output, &wg)
}
}

// Wait for all output processing to complete
wg.Wait()

fmt.Println("All subprocesses and outputs have been processed.")
}
```



example concurrent config.json
```json
{
  "mode": "concurrent",
  "filePrefix": "output_",
  "mqttTopic": "fuzzing/crashes",
  "commands": [
    {
      "filePath": "/path/to/first/file",
      "args": ["arg1", "arg2", "arg3"]
    },
    {
      "filePath": "/path/to/second/file",
      "args": ["arg4", "arg5", "arg6"]
    }
  ]
}
```

run the program

```sh
go run main.go
```

**Comment by Rhernandez513** [comment]
pseudo code docker compose:

```yaml
docker compose yaml

version: "3.8"

services:
  # Go application container
  go-app:
    build: .
    container_name: go-app
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto:1883  # Set the MQTT broker URL to the Mosquitto container
    depends_on:
      - mosquitto  # Wait for the Mosquitto broker to be up before starting the Go app
    volumes:
      - ./config:/app/config  # Mount config directory to container (optional)
    networks:
      - mqtt-network

  # MQTT Broker container (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"  # Expose MQTT port
    volumes:
      - mosquitto-data:/mosquitto/data  # Store persistent MQTT data
      - mosquitto-config:/mosquitto/config  # Mosquitto config (optional)
    networks:
      - mqtt-network

# Define networks for internal communication
networks:
  mqtt-network:
    driver: bridge

# Volumes for persistent data
volumes:
  mosquitto-data:
  mosquitto-config:
```

**Comment by Rhernandez513** [comment]
pseudo modified publishtoMQTT function (now that we are using a MQTT broker in the pod instead of in the process)

```golang
import (
"fmt"
"os"
"[github.com/eclipse/paho.mqtt.golang](http://github.com/eclipse/paho.mqtt.golang)"
)

func publishToMQTT(output string) error {
// Retrieve the MQTT broker URL from the environment variable
mqttBrokerURL := os.Getenv("MQTT_BROKER_URL")
if mqttBrokerURL == "" {
return fmt.Errorf("MQTT broker URL is not set")
}

// Set up MQTT client options
opts := mqtt.NewClientOptions().AddBroker(mqttBrokerURL).SetClientID("go-client")
client := mqtt.NewClient(opts)

// Connect to the MQTT broker
if token := client.Connect(); token.Wait() && token.Error() != nil {
return fmt.Errorf("error connecting to MQTT broker: %w", token.Error())
}

// Publish the output to the MQTT topic
token := client.Publish("fuzzing/crashes", 0, false, output)
token.Wait()

// Disconnect from the broker
client.Disconnect(250)

fmt.Printf("Output published to MQTT topic: fuzzing/crashes\n")
return nil
}
```

**Comment by Rhernandez513** [comment]
pseudo dockerfile for `main.go`

```Dockerfile
dockerfile for main.go

# Use the official Golang image to build the Go application
FROM golang:1.20 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the Go source code into the container's working directory
COPY . .

# Install Go dependencies (if using Go modules)
# RUN go mod tidy  # Uncomment this line if you're using Go modules

# Build the Go program (this creates the binary 'app')
RUN go build -o app .

# Use a minimal base image for the final container (no need to include MQTT client since it will connect via network)
FROM debian:bullseye-slim

# Install necessary packages (for example, certificates)
RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled binary from the build stage
COPY --from=build /app/app .

# Copy the config directory into the container (the config.json file should be here)
COPY ./config /app/config

# Expose any necessary ports (this is just an example, not required for MQTT)
# EXPOSE 1883  # MQTT is on the Mosquitto container, not the Go app

# Set the entry point to run the compiled Go application
ENTRYPOINT ["./app"]
```

**Comment by Rhernandez513** [comment]
simple kubernetes deployment manifest for a potential golang fuzzing service and config map with MQTT

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: your-registry/your-go-app-image:latest  # Replace with your image
          env:
            - name: MQTT_BROKER_URL
              value: "mqtt://mosquitto:1883"  # Mosquitto broker hostname (service name in Kubernetes)
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: go-app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883  # Default MQTT port
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080  # Example port where your Go app may be exposed
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
data:
  config.json: |
    {
      "mode": "concurrent",
      "filePrefix": "output_",
      "mqttTopic": "fuzzing/crashes",
      "commands": [
        {
          "filePath": "/path/to/first/file",
          "args": ["arg1", "arg2", "arg3"]
        },
        {
          "filePath": "/path/to/second/file",
          "args": ["arg4", "arg5", "arg6"]
        }
      ]
    }
```
